/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.util.Random;
import javax.swing.JFrame;

/**
 *
 * @author Will
 */
public class ticTacTwo extends javax.swing.JFrame {
    /**
     * Creates new form ticTac
     */
    static int [] board;
    static boolean yourTurn;
    public ticTacTwo(int[] spaces, boolean turn) {
        board = spaces;
        setResizable(false);
        yourTurn = turn;
        if (board[0] != 0) {
            if (board[1] != 0) {
                if (board[2] != 0) {
                    if (board[3] != 0) {
                        if (board[4] != 0) {
                            if (board[5] != 0) {
                                if (board[6] != 0) {
                                    if (board[7] != 0) {
                                        if (board[8] != 0) {
                                            Draw d = new Draw();
                                            setVisible(false);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    
                }
            }
        }
        initComponents();
        if (!turn) {
            Random random = new Random();
            int AISpace = random.nextInt(8);
            if (board[AISpace] == 0) {
            board[AISpace] = -1;
                if (boardCheck()) {
                   Lose l = new Lose();
                    setVisible(false);
                } else {
                    ticTacTwo t = new ticTacTwo(board, true);
                    setVisible(false);
                }   
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
            }
            
            
            
            
        } else {
            setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        String[] boardDisplay = new String[9];
        for (int i = 0; i < 9; i ++) {
            if(board[i] == -1) {
                boardDisplay[i] = "O";
            } else if (board[i] == 1) {
                boardDisplay[i] = "X";
            } else {
                boardDisplay[i] = "-";
            }
        }
        
        jButton1.setText(boardDisplay[0]);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(boardDisplay[1]);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(boardDisplay[3]);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(boardDisplay[6]);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(boardDisplay[2]);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(boardDisplay[4]);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(boardDisplay[5]);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(boardDisplay[7]);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText(boardDisplay[8]);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Lawful good 1
        if (board[0] == 0) {
            board[0] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                w.setVisible(true);
                w.setResizable(false);
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Neutral Good 2 
        if (board[1] == 0) {
            board[1] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Lawful neutral 4
        if (board[3] == 0) {
            board[3] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Lawful evil 7
        if (board[6] == 0) {
            board[6] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Chaotic Good 3 
        if (board[2] == 0) {
            board[2] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // True Neutral 5
        if (board[4] == 0) {
            board[4] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Chaotic Neutral 6
        if (board[5] == 0) {
            board[5] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Neutral Evil 8
        if (board[7] == 0) {
            board[7] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // chaotic Evil 9
        if (board[8] == 0) {
            board[8] = 1;
            if (boardCheck()) {
                WinTic w = new WinTic();
                setVisible(false);
            } else {
                ticTacTwo t = new ticTacTwo(board, false);
                setVisible(false);
            }   
        } else {
            ticTacTwo t = new ticTacTwo(board, true);
        }
    }    
    
    private boolean boardCheck() {
        if (board[0] == board[3] && board[0] == board[6] && board[0] != 0) {
            return true;
        }
        if (board[1] == board[4] && board[1] == board[7] && board[1] != 0) {
            return true;
        }
        if (board[2] == board[5] && board[2] == board[8] && board[2] != 0) {
            return true;
        }
        if (board[0] == board[1] && board[0] == board[2] && board[0] != 0) {
            return true;
        }
        if (board[3] == board[4] && board[3] == board[5] && board[3] != 0) {
            return true;
        }
        if (board[6] == board[7] && board[6] == board[8] && board[6] != 0) {
            return true;
        }
        if (board[0] == board[4] && board[0] == board[8] && board[0] != 0) {
            return true;
        }
        if (board[2] == board[4] && board[2] == board[6] && board[2] != 0) {
            return true;
        }
        
        
        
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticTacTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticTacTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticTacTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticTacTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticTacTwo(board, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
